### ISSUE TITLE
/Users/mg/Documents/Grails/GGTS3.6.3-SR1-2/Demo/Pods/JazzHands/JazzHands/IFTTTConstraintConstantAnimation.m:18:17: Method override for the designated initializer of the superclass '-init' not found

### ISSUE THREAD

**Issue by confile** [IFTTT/JazzHands#1705]
Using Swift 2.0 in Xcode7 I get the following warnings: 

```
/Users/mg/Documents/Grails/GGTS3.6.3-SR1-2/Demo/Pods/JazzHands/JazzHands/IFTTTConstraintConstantAnimation.m:18:17: Method override for the designated initializer of the superclass '-init' not found

/Users/mg/Documents/Grails/GGTS3.6.3-SR1-2/Demo/Pods/JazzHands/JazzHands/IFTTTConstraintMultiplierAnimation.m:21:17: Method override for the designated initializer of the superclass '-init' not found

/Users/mg/Documents/Grails/GGTS3.6.3-SR1-2/Demo/Pods/JazzHands/JazzHands/IFTTTLabelAnimation.m:17:17: Method override for the designated initializer of the superclass '-init' not found
```

Could you please fix that.

**Comment by RGSSoftware** [comment]
Did you try https://github.com/IFTTT/RazzleDazzle. RazzleDazzle is from the creators of JazzHands, but written entirely in Swift 2.0.

**Comment by lauraskelton** [comment]
@confile I'd also suggest using https://github.com/IFTTT/RazzleDazzle if you're working with Swift 2.0, since it's already written in Swift.

If you want to keep using JazzHands, you'll need to update to the most recent version of the pod - `IFTTTLabelAnimation` hasn't been around for several months. We have `IFTTTTextColorAnimation` now that I believe implements a similar animation.
